import turtle

turtle.showturtle()

turtle.circle(100)
turtle.penup()
turtle.goto(0,188)
turtle.pendown()
turtle.write("12")
turtle.penup()
turtle.goto(12,0)
turtle.pendown()
turtle.write("6")
turtle.penup()
turtle.goto(95,100)
turtle.pendown()
turtle.write("3")
turtle.penup()
turtle.goto(-95,100)
turtle.pendown()
turtle.write("9")
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.pensize(0.25)
turtle.forward(60)
turtle.penup()
turtle.goto(0,100)
turtle.right(180)
turtle.pendown()
turtle.pensize(1)
turtle.forward(60)
turtle.penup()
turtle.goto(0,100)
turtle.right(90)
turtle.pendown()
turtle.pensize(2)
turtle.forward(75)

turtle.done()